### ISSUE TITLE
Extension fails to start due to CSP error

### ISSUE THREAD

**Issue by Spurlos** [Zortrox/steamchecker#14]
Using Chrome Beta 130 and I have started getting the following error while the extension tires to start:

```
Refused to load the script 'chrome-extension://82f4afa8-5c67-41c6-bde0-f31887f3fb17/assets/content.ts-CfJfSHwP.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
(anonymous)	@	content.ts-loader-CDQca05a.js:8
```

It seems a misconfiguration of Manifest V3 for the CSP policies.
![image](https://github.com/user-attachments/assets/fa176d6f-a619-4185-96f7-2fb0b2466894)

Unfortunately i can't go back to Chrome stable, but I believe it has\will get the same behaviour when v130 lands in stable.

**Comment by Zortrox** [comment]
Thank you for catching that!  I have a workaround fix in [version 1.0.1](https://github.com/Zortrox/steamchecker/releases/tag/v1.0.1) if you want to test on your end.  I submitted this to the Chrome Web Store already and am just waiting for Google to review it.

For reference, I used a fix by [another developer](https://github.com/crxjs/chrome-extension-tools/issues/918#issuecomment-2375616794) since the [build tool I have hasn't fixed this](https://github.com/crxjs/chrome-extension-tools/issues/918) on their end yet.  I'll leave this open until I confirm the store version is working.
